### PR TITLE
Create Final List of Airdrop 

### PR DESCRIPTION
**Pull request by sifmoon**

### CODE REVIEW

**Comment by dluks82** [comment]
> _No description provided._

Many people complaining about TG Sifchain for being left out of the final list even though they met all the requirements to be eligible. I even

**Comment by sml1991** [comment]
please guys, i found that im not on the final list but i now know why.
there is a blank space at the end of my sifaddress. i foud it in the old list 

https://github.com/Sifchain/airdrop/blob/main/extracts/community_token_giveaway_submissions.csv#L1847

i did everything correctly besides this. i don't know how this happend. please have tolerance. would be a pitty to be kicked out because of an empty space.

**Comment by zhouweinihao** [comment]
please guys, i found that im not on the final list but i now know why.
there is a blank space at the end of my sifaddress. i foud it in the old list
https://github.com/Sifchain/airdrop/blob/main/extracts/community_token_giveaway_submissions.csv#L127
i did everything correctly besides this. i don't know how this happend. please have tolerance. would be a pitty to be kicked out because of an empty space

**Comment by TymurTarasov** [comment]
Снимок экрана 2021-04-11 в 16 11 02
Friends, hello! I used to be on the list for the awards, but the final version does not have my address (((please check! Thank you in advance!
https://twitter.com/AlfafarTimur/status/1362868468362727425 Here is a link to my tweet

**Comment by Magvin** [comment]
Same here, sif1nk3a87z04xkrp96zwt7l49mmxny7y738numd5p

Is on the list of airdrop with correct Twitter handle. At some point they banned my twitter :/

**Review by alijnmerchant21 — APPROVED** [review]

**Comment by Caixuchu1985** [comment]
Same here, I was in the previous list: sif172ltdaresunfgg5pcdngjcnutte4mmjw7l2aef
check my twitter:  https://twitter.com/sifchain/status/1381419769761435648?s=20
Please please add my address, I didn't do anything wrong.
Thanks in advance

**Comment by chuizi01** [comment]
Hello friend! I used to be on the list of winners, but the final version did not have my address.
In the airdrop list with the correct Twitter handle. At some point, they banned my Twitter and I can provide screenshots of the task.   sif1gj4dyz92vl4drr2lrtdevq5uwdevwga4q0glyy
获奖名单
转推链接

**Comment by johnc76** [comment]
Hi man, I’m on this list and my twitter profile is too, but my tweet isn’t - it’s my pinned post. The tweet link is: https://twitter.com/johncon49337454/status/1362735519776591874?s=21

My profile name is @JohnCon49337454

sorry if you have all this info already.

thanks,
John

**Comment by IrinaLavrinova** [comment]
Good afternoon, please check my account! I am not on the list for getting an airdrop but I have fulfilled all the conditions
https://twitter.com/Anna99365142/status/1362668918238806016 
My Sif address: sif1m9x4gg6frezyeqldxdz4dvegxpcytxna8xlnls 
And contrib. code: c80ffe8aab3b388d318afdb8bbec0288234cfcd398a1fcb5e4652fc54ba7bf3c 
For some reason, the contributory code is not listed in this list.  https://github.com/Sifchain/airdrop/blob/caseyturnerarrington-patch-1/extracts/token_sale_contribution_codes3.csv Please check it out! Thank you!

**Comment by mrdaddyru** [comment]
Please check sif13v6ju8zc2j65anh8mavgvzxja8y5w47shydg3x KYC passed, twitter https://twitter.com/whypru/status/1362810290824482820. Not included in the list 
image

**Comment by Dluks82** [comment]
Hey team, I’ve confirmed all the information and requirements to be on the distribution list, please check, I’m sure they’ll do a fair process... 

Twitter: @duks82 
Sif address: sif10f2eyvuvmujq0t7l63fec2s9wqwlufgxgqe8jz
Unique Contribution Code:
51f466b323709979c67f65a333e17400a86fe7c2b85e6358216e4d8cf90777e9

IMG_20210412_093441
Screenshot_20210411-215417__01
Screenshot_20210412-093836

**Comment by Dluks82** [comment]
Hey team, I’ve confirmed all the information and requirements to be on the distribution list, please check, I’m sure they’ll do a fair process... 

Twitter: @duks82
Sif address: sif1e5vwy6d7pllz6yuxlxc2cn0jqqy3t2q5skm9hz
Your Unique Contribution Code:
51f466b323709979c67f65a333e17400a86fe7c2b85e6358216e4d8cf90777e9

Screenshot_20210412-093836
Screenshot_20210411-215417__01
IMG_20210412_093441

**Review by alijnmerchant21 — APPROVED** [review]

**Comment by Damian00000** [comment]
I'm not on the new list again. Please tell me what I did wrong.
My Sif address:  sif1ltl0r2ywhwyle68sjylkshjzncap393e6ce3wx

https://twitter.com/Denis24534/status/1362653927330766848

**Comment by KAZ7172** [comment]
I am not on the second list. Add me please: sif16dw04d7mmr3jget4cl9catc52k23kxq6avkgpn

**Pull request merged**
